# Generated by Django 3.1.5 on 2021-02-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210131_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Статьи', 'verbose_name_plural': 'Cтатьи'},
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='media/', verbose_name='Ссылка картинки'),
        ),
    ]
