# Generated by Django 3.1.5 on 2021-02-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210201_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('des', models.TextField(verbose_name='Описание')),
                ('cover', models.ImageField(help_text='150x150px', upload_to='media/', verbose_name='картинки')),
            ],
            options={
                'verbose_name': 'Статьи1',
                'verbose_name_plural': 'Cтатьи1',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
