# Generated by Django 3.1.5 on 2021-02-03 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210203_2258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
