# Generated by Django 3.1.5 on 2021-02-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=4096)),
            ],
            options={
                'verbose_name': 'коментарий',
                'verbose_name_plural': 'коментарии',
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
