# Generated by Django 3.1.5 on 2021-03-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210214_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titl', models.CharField(max_length=50, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(help_text='150x150px', upload_to='media/', verbose_name='картинки')),
            ],
            options={
                'verbose_name': 'Биография кота',
                'verbose_name_plural': 'Биография кота',
            },
        ),
    ]
